finished user login, logout in views.py, add a model and a serializer to user-session, added consumer to auth-service. added proper urls for user-session.

diff --git a/Backend/auth_service/Dockerfile b/Backend/auth_service/Dockerfile
--- a/Backend/auth_service/Dockerfile
+++ b/Backend/auth_service/Dockerfile
@@ -3,29 +3,42 @@ FROM alpine:3.20
 ENV PYTHONUNBUFFERED=1
 ENV LANG=C.UTF-8
 
-USER root
 # Update and install dependencies
 # trunk-ignore(hadolint/DL3018)
-RUN apk update && apk add --no-cache \
-	python3 py3-pip postgresql16 postgresql16-client \
-    bash curl openssl build-base libffi-dev python3-dev && \
-    mkdir /run/postgresql && \
-    chown -R postgres:postgres /run/postgresql
+RUN apk update && apk add --no-cache python3 py3-pip \
+postgresql16 postgresql16-client \
+bash supervisor curl openssl bash \
+build-base libffi-dev python3-dev
+# Set work directory
+RUN mkdir /run/postgresql && \
+    chown postgres:postgres /run/postgresql && \
+    mkdir /app && chown -R postgres:postgres /app
+
 WORKDIR /app/
-RUN chown -R postgres:postgres /app/ && \
-python3 -m venv venv && chown -R postgres:postgres venv
 
+# Install Python virtual environment
+RUN python3 -m venv venv && chown -R postgres:postgres venv
+
+# Copy application code and adjust permissions
+COPY --chown=postgres:postgres ./Backend/auth_service/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
 COPY --chown=postgres:postgres ./Backend/auth_service/requirements.txt .
-
-# Copy the rest of the application code
 COPY --chown=postgres:postgres ./Backend/auth_service/auth_service /app/auth_service
-
-# Copy and set permissions for the entrypoint script
 COPY --chown=postgres:postgres ./Backend/auth_service/tools.sh /app
 COPY --chown=postgres:postgres ./Backend/auth_service/init_database.sh /app
-RUN chmod +x /app/tools.sh /app/init_database.sh && chown -R postgres:postgres /app/auth_service/user_auth/
+COPY --chown=postgres:postgres ./Backend/auth_service/run_consumer.sh /app
+
+# Ensure supervisord and scripts are executable and owned by postgres
+RUN chown -R postgres:postgres /etc/supervisor && \
+    chown -R postgres:postgres /usr/bin/supervisord && \
+    chown -R postgres:postgres /etc/supervisor/conf.d/supervisord.conf && \
+    chown -R postgres:postgres /app && \
+    chown -R postgres:postgres /var/log && \
+    chown -R postgres:postgres /app/venv && \
+    chown -R postgres:postgres /app/auth_service && \
+    chmod +x /usr/bin/supervisord
+
 USER postgres
 
-# Add HEALTHCHECK instruction with delay
-HEALTHCHECK --interval=30s --timeout=2s --start-period=60s --retries=3 CMD curl -sSf http://localhost:8000/auth/login/ > /dev/null &&  echo "success" || echo "failure"
-ENTRYPOINT [ "sh", "./tools.sh" ]
+HEALTHCHECK --interval=30s --timeout=2s --start-period=5s --retries=3 CMD curl --fail --silent --write-out http://127.0.0.1:8000/ > /dev/null &&  echo "success" || echo "failure"
+
+ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
