Updated Makefile to free up the port if it's already allocated, configured Frontend service to run the service temporarily, we still need more configuration, we added ownership to postgres user and to run containers to use postgres user inside of user_management and auth_service, added rabbitmq user and gave ownership to the user for rabbitmq container and fixed all the linting errors using trunk app

diff --git a/Backend/auth_service/Dockerfile b/Backend/auth_service/Dockerfile
--- a/Backend/auth_service/Dockerfile
+++ b/Backend/auth_service/Dockerfile
@@ -3,30 +3,31 @@ FROM alpine:3.20
 ENV PYTHONUNBUFFERED=1
 ENV LANG=C.UTF-8
 
-# Update and install dependencies
-RUN apk update && apk add --no-cache python3 py3-pip postgresql-client postgresql bash
-
 USER root
-# Set work directory
-RUN mkdir /run/postgresql
-RUN chown postgres:postgres /run/postgresql
-
+# Update and install dependencies
+RUN apk update && apk add --no-cache \
+	python3=3.12.3-r1 \
+    py3-pip=24.0-r2 \
+    postgresql16=16.3-r0 \
+    postgresql16-client=16.3-r0 \
+    bash=5.2.26-r0 && \
+    mkdir /run/postgresql && \
+    chown -R postgres:postgres /run/postgresql
 WORKDIR /app/
-RUN chown -R postgres:postgres /app/
+RUN chown -R postgres:postgres /app/ && \
+python3 -m venv venv && chown -R postgres:postgres venv
 
-RUN python3.12 -m venv venv && chown -R postgres:postgres venv
-
-COPY ./Backend/auth_service/requirements.txt .
+COPY --chown=postgres:postgres ./Backend/auth_service/requirements.txt .
 
 # Copy the rest of the application code
-COPY ./Backend/auth_service/auth_service /app/auth_service
+COPY --chown=postgres:postgres ./Backend/auth_service/auth_service /app/auth_service
 
 # Copy and set permissions for the entrypoint script
-COPY ./Backend/auth_service/tools.sh /app
-COPY ./Backend/auth_service/init_database.sh /app
+COPY --chown=postgres:postgres ./Backend/auth_service/tools.sh /app
+COPY --chown=postgres:postgres ./Backend/auth_service/init_database.sh /app
 RUN chmod +x /app/tools.sh /app/init_database.sh && chown -R postgres:postgres /app/auth_service/user_auth/
 USER postgres
 
-# Add HEALTHCHECK instruction
-HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD wget -q --spider http://localhost:8000/auth/api/token/ || exit 1
+# Add HEALTHCHECK instruction with delay
+HEALTHCHECK --interval=30s --timeout=2s --start-period=60s --retries=3 CMD curl -sSf http://localhost:8000/auth/api/token/ > /dev/null &&  echo "success" || echo "failure"
 ENTRYPOINT [ "sh", "./tools.sh" ]
diff --git a/Backend/rabbitmq/Dockerfile b/Backend/rabbitmq/Dockerfile
--- a/Backend/rabbitmq/Dockerfile
+++ b/Backend/rabbitmq/Dockerfile
@@ -1,13 +1,13 @@
 FROM alpine:3.20
 
-RUN apk add --no-cache erlang openssl bash
+RUN apk add --no-cache erlang=26.2.5-r0 openssl=3.3.1-r0 bash=5.2.26-r0 curl=8.7.1-r0 xz=5.6.1-r3
 
 # Set environment variable for RabbitMQ installation directory
 RUN addgroup -S rabbitmq && adduser -S rabbitmq -G rabbitmq
 ENV RABBITMQ_HOME=/usr/local/bin/rabbitmq_server-3.13.3
 RUN mkdir -p $RABBITMQ_HOME && chown -R rabbitmq:rabbitmq /usr/local/bin/ && \
     # Download and install RabbitMQ
-    wget https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.13.3/rabbitmq-server-generic-unix-3.13.3.tar.xz && \
+    curl -L -o rabbitmq-server-generic-unix-3.13.3.tar.xz https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.13.3/rabbitmq-server-generic-unix-3.13.3.tar.xz && \
     tar xvf rabbitmq-server-generic-unix-3.13.3.tar.xz -C /usr/local/bin/ && \
     rm rabbitmq-server-generic-unix-3.13.3.tar.xz
 
@@ -21,7 +21,7 @@ RUN rabbitmq-plugins enable rabbitmq_management
 EXPOSE 5672 15672
 
 # Add HEALTHCHECK instruction
-HEALTHCHECK --interval=30s --timeout=5s CMD rabbitmqctl node_health_check || exit 1
+HEALTHCHECK --interval=30s --timeout=2s CMD curl -sSf http://localhost:15672 > /dev/null &&  echo "success" || echo "failure"
 
 # Run RabbitMQ server
-CMD ["rabbitmq-server", "detached"]
+CMD ["rabbitmq-server"]
diff --git a/Backend/user_management/Dockerfile b/Backend/user_management/Dockerfile
--- a/Backend/user_management/Dockerfile
+++ b/Backend/user_management/Dockerfile
@@ -4,8 +4,7 @@ ENV PYTHONUNBUFFERED=1
 ENV LANG=C.UTF-8
 
 # Update and install dependencies
-RUN apk update && apk add --no-cache python3 py3-pip postgresql-client postgresql bash supervisor curl
-
+RUN apk update && apk add --no-cache python3=3.12.3-r1 py3-pip=24.0-r2 postgresql16=16.3-r0 postgresql16-client=16.3-r0 bash=5.2.26-r0 supervisor=4.2.5-r5 curl=8.7.1-r0
 # Set work directory
 RUN mkdir /run/postgresql && \
     chown postgres:postgres /run/postgresql && \
@@ -14,7 +13,7 @@ RUN mkdir /run/postgresql && \
 WORKDIR /app/
 
 # Install Python virtual environment
-RUN python3.12 -m venv venv && chown -R postgres:postgres venv
+RUN python3 -m venv venv && chown -R postgres:postgres venv
 
 # Copy application code and adjust permissions
 COPY --chown=postgres:postgres ./Backend/user_management/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
@@ -37,6 +36,6 @@ RUN chown -R postgres:postgres /etc/supervisor && \
 
 USER postgres
 
-HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD curl --failed http://localhost:8000/user/register/ || exit 1
+HEALTHCHECK --interval=30s --timeout=2s --start-period=5s --retries=3 CMD curl -sSf http://localhost:8000/user/register/ > /dev/null &&  echo "success" || echo "failure"
 
 ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
diff --git a/Frontend/Dockerfile b/Frontend/Dockerfile
--- a/Frontend/Dockerfile
+++ b/Frontend/Dockerfile
@@ -1,17 +1,22 @@
 FROM alpine:3.20 AS frontend
 
-RUN apk update && apk add --no-cache nginx openrc openssl openssh
+RUN apk update && apk add --no-cache nginx=1.26.1-r0 openrc=0.54-r1 openssl=3.3.1-r0 openssh=9.7_p1-r3
 
 RUN addgroup -S www && adduser -D -S -G www www && \
 mkdir -p /www && \
 chown -R www:www /var/lib/nginx && \
+chown -R www:www /var/lib/nginx/logs/ && \
 chown -R www:www /www && \
 mkdir -p /etc/nginx/ssl && \
-chown -R www:www /etc/nginx/ssl
-COPY --chown=www:www Frontend/index.html /www/index.html
-COPY --chown=www:www Frontend/tools.sh /tools.sh
-RUN chmod +x /tools.sh
-COPY --chown=www:www Frontend/nginx.conf /etc/nginx/nginx.conf
-HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl --fail http://localhost:443 || exit 1
+chown -R www:www /etc/nginx/ssl && \
+chown -R www:www /etc/nginx
+COPY --chown=www:www ./Frontend/index.html /www/index.html
+WORKDIR /app
+COPY --chown=www:www ./Frontend/tools.sh /app/tools.sh
+RUN chmod +x /app/tools.sh
+
+COPY --chown=www:www ./Frontend/nginx.conf /etc/nginx/nginx.conf
+HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl -sSf http://localhost:443 > /dev/null &&  echo "success" || echo "failure"
+RUN chown -R www:www /run/nginx
 USER www
-CMD ["sh", "./tools.sh"]
+CMD ["sh", "tools.sh"]
